services:
  - type: web
    name: insurance-dashboard
    runtime: python3
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_PORT
        value: "3001"
      - key: FLASK_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: postgres_db
          property: connectionString

databases:
  - name: postgres_db
    databaseName: insurance_details
    user: insurance_details_user
    plan: starter
